version: "{build}"

environment:
  nodejs_version: "5"

matrix:
  fast_finish: true

install:
  - choco install firefox
  - choco upgrade firefox
  - choco install googlechrome
  - choco upgrade googlechrome
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
